# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

# Groups
- id: primary-standalone-ceph-mon
  type: group
  role: [primary-standalone-ceph-mon]
  requires: [controller]
  required_for: [ceph-osd]
  tasks: [enable_rados-for-standalone-ceph,standalone-ceph-radosgw,task-standalone-ceph-mon,hiera-override-for-standalone-ceph,firewall,hiera,tools,netconfig,connectivity_tests,globals,fuel_pkgs,logging,hosts,apache,openstack-haproxy,virtual_ips,ssl-add-trust-chain]
  parameters:
    strategy:
      type: one_by_one

- id: standalone-ceph-mon
  type: group
  role: [standalone-ceph-mon]
  requires: [primary-standalone-ceph-mon]
  required_for: [deploy_end]
  tasks: [enable_rados-for-standalone-ceph,standalone-ceph-radosgw,task-standalone-ceph-mon,hiera-override-for-standalone-ceph,firewall,hiera,tools,netconfig,connectivity_tests,globals,fuel_pkgs,logging,hosts,apache,openstack-haproxy,virtual_ips,ssl-add-trust-chain]
  parameters:
    strategy:
      type: parallel

# Turn off ceph on controller
- id: ceph-mon
  type: skipped

- id: ceph-radosgw
  type: skipped

- id: openstack-haproxy-radosgw
  type: skipped

- id: swift-keystone
  type: skipped

#- id: ceph_create_pools
#  type: skipped

#- id: ceph_ready_check
#  type: skipped

- id: enable_rados
  type: skipped

# Override hiera for at least primary_mon value
- id: hiera-override-for-standalone-ceph
  type: puppet
  groups: [ceph-osd,primary-standalone-ceph-mon,standalone-ceph-mon,compute,primary-controller,controller]
  requires: [globals]
  required_for: [task-standalone-ceph-mon,top-role-ceph-osd,deploy_end]
  parameters:
    puppet_manifest: 'hiera-override.pp'
    puppet_modules: 'modules:/etc/puppet/modules'
    timeout: 120

# Standalone mons
- id: task-standalone-ceph-mon
  type: puppet
  required_for: [deploy_end]
  requires: [connectivity_tests,hiera]
  parameters:
    puppet_manifest: 'mon.pp'
    puppet_modules: 'modules:/etc/puppet/modules'
    timeout: 3600

#RadosGW deployment
- id: cluster-for-standalone-ceph
  type: puppet
  groups: [primary-standalone-ceph-mon,standalone-ceph-mon]
  required_for: [virtual_ips,deploy_end]
  requires: [hosts, firewall, deploy_start]
  parameters:
    puppet_manifest: 'cluster.pp'
    puppet_modules: 'modules:/etc/puppet/modules'
    timeout: 3600

- id: cluster-haproxy-for-standalone-ceph
  type: puppet
  groups: [primary-standalone-ceph-mon,standalone-ceph-mon]
  required_for: [deploy_end]
  requires: [deploy_start, cluster-for-standalone-ceph, virtual_ips]
  parameters:
    puppet_manifest: 'cluster-haproxy.pp'
    puppet_modules: 'modules:/etc/puppet/modules'
    timeout: 3600

- id: openstack-haproxy-radosgw-for-standalone-ceph
  type: puppet
  groups: [primary-standalone-ceph-mon,standalone-ceph-mon]
  required_for: [openstack-haproxy, deploy_end]
  requires: [deploy_start, cluster-haproxy-for-standalone-ceph, hiera-override-for-standalone-ceph]
  parameters:
    puppet_manifest: 'openstack-haproxy-radosgw.pp'
    puppet_modules: 'modules:/etc/puppet/modules'
    timeout: 300

- id: standalone-ceph-radosgw
  type: puppet
  groups: [primary-standalone-ceph-mon,standalone-ceph-mon]
  required_for: [deploy_end]
  requires: [apache,task-standalone-ceph-mon]
  parameters:
    puppet_manifest: 'radosgw.pp'
    puppet_modules: 'modules:/etc/puppet/modules'
    timeout: 3600

- id: standalone-ceph-rados-pki
  type: puppet
  groups: [primary-standalone-ceph-mon,standalone-ceph-mon]
  required_for: [deploy_end]
  requires: [standalone-ceph-radosgw]
  condition: "settings:token-provider.token_provider.value == 'pki' or settings:token-provider.token_provider.value == 'pkiz'"
  parameters:
    puppet_manifest: 'rados-pki.pp'
    puppet_modules: 'modules:/etc/puppet/modules'
    timeout: 3600

- id: enable_rados-for-standalone-ceph
  type: puppet
  groups: [primary-standalone-ceph-mon,standalone-ceph-mon]
  condition: "settings:storage.objects_ceph.value == true"
  requires: [standalone-ceph-rados-pki]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/ceph/enable_rados.pp
    puppet_modules: /etc/puppet/modules
    timeout: 180
    cwd: /

#POSTDEPLOYMENT
#- id: ceph_create_pools-for-standalone-ceph
#  type: puppet
#  role: [primary-standalone-ceph-mon,standalone-ceph-mon]
#  requires: [post_deployment_start]
#  required_for: [ceph_ready_check-for-standalone-ceph]
#  condition: "settings:storage.objects_ceph.value == true or settings:storage.images_ceph.value == true or settings:storage.volumes_ceph.value == true or settings:storage.ephemeral_ceph.value == true"
#  parameters:
#    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/ceph/ceph_pools.pp
#    puppet_modules: /etc/puppet/modules
#    timeout: 3600
#    cwd: /

#- id: ceph_ready_check-for-standalone-ceph
#  type: shell
#  role: [primary-standalone-ceph-mon]
#  condition: "settings:storage.objects_ceph.value == true or settings:storage.images_ceph.value == true or settings:storage.volumes_ceph.value == true or settings:storage.ephemeral_ceph.value == true"
#  requires: [post_deployment_start]
#  required_for: [enable_rados-for-standalone-ceph, upload_cirros]
#  parameters:
#    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/ceph/ceph_ready_check.rb
#    timeout: 1800

- id: ceph_client
  type: puppet
  role: [primary-controller,controller]
  requires: [post_deployment_start]
  required_for: [ceph_create_pools,ceilometer-radosgw-user,post_deployment_end]
  condition: "settings:storage.objects_ceph.value == true or settings:storage.images_ceph.value == true or settings:storage.volumes_ceph.value == true or settings:storage.ephemeral_ceph.value == true"
  parameters:
    puppet_manifest: 'ceph_client.pp'
    puppet_modules: 'modules:/etc/puppet/modules'
    timeout: 3600

- id: dns-client-for-standalone-ceph
  type: puppet
  role: [primary-standalone-ceph-mon,standalone-ceph-mon]
  requires: [post_deployment_start]
  required_for: [ntp-client-for-standalone-ceph]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/dns/dns-client.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
    cwd: /

- id: ntp-client-for-standalone-ceph
  type: puppet
  role: [primary-standalone-ceph-mon,standalone-ceph-mon]
  requires: [dns-client-for-standalone-ceph]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/ntp/ntp-client.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
    cwd: /

- id: configure-default-route-ceph-mon
  type: puppet
  role: [primary-standalone-ceph-mon,standalone-ceph-mon]
  requires: [post_deployment_start]
  required_for: [post_deployment_end]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/netconfig/configure_default_route.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
    cwd: /
