# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

- id: ceph-mon
  type: skipped

- id: standalone-ceph-mon
  type: puppet
  groups: [detached-ceph-mon]
  required_for: [deploy_end, controller_remaining_tasks]
  requires: [openstack-controller]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/ceph/mon.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: detached-ceph-mon
  type: group
  role: [detached-ceph-mon]
  parameters:
    strategy:
      type: parallel

#- id: detach-ceph-mon-deployment-puppet
#  type: puppet
#  groups: [detach-ceph-mon]
#  required_for: [deploy_end]
#  requires: [deploy_start]
#  parameters:
#    puppet_manifest: "deploy.pp"
#    puppet_modules: ""
#    timeout: 3600

#- id: detach-ceph-mon-post-deployment-sh
#  type: shell
#  role: [detach-ceph-mon]
#  required_for: [post_deployment_end]
#  requires: [post_deployment_start]
#  parameters:
#    cmd: echo post_deployment_task_executed > /tmp/post_deployment
#    retries: 3
#    interval: 20
#    timeout: 180

#- id: detach-ceph-mon-pre-deployment-sh
#  type: shell
#  role: [detach-ceph-mon]
#  required_for: [pre_deployment_end]
#  requires: [pre_deployment_start]
#  parameters:
#    cmd: echo pre_deployment_task_executed > /tmp/pre_deployment
#    retries: 3
#    interval: 20
#    timeout: 180
