# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

# Groups
- id: primary-standalone-ceph-mon
  type: group
  role: [primary-standalone-ceph-mon]
  requires: [deploy_start]
  required_for: [ceph-osd]
  tasks: [task-standalone-ceph-mon,hiera-override-for-standalone-ceph]
  parameters:
    strategy:
      type: one_by_one

- id: standalone-ceph-mon
  type: group
  role: [standalone-ceph-mon]
  requires: [primary-standalone-ceph-mon]
  required_for: [deploy_end]
  tasks: [task-standalone-ceph-mon,hiera-override-for-standalone-ceph]
  parameters:
    strategy:
      type: parallel

# Product tasks
- id: task-standalone-ceph-mon
  type: puppet
  required_for: [deploy_end]
  requires: [connectivity_tests,hiera-override-for-standalone-ceph]
  parameters:
    puppet_manifest: 'mon.pp'
    puppet_modules: 'modules:/etc/puppet/modules'
    timeout: 3600

# Override hiera for at least primary_mon value
- id: hiera-override-for-standalone-ceph
  type: puppet
  groups: [ceph-osd,primary-standalone-ceph-mon,standalone-ceph-mon,compute]
  requires: [globals-for-standalone-ceph]
  required_for: [task-standalone-ceph-mon,top-role-ceph-osd,ceph-compute]
  parameters:
    puppet_manifest: 'hiera-override.pp'
    puppet_modules: 'modules:/etc/puppet/modules'
    timeout: 120

# Turn off ceph-mon on controller
- id: ceph-mon
  type: skipped

# - id: ceph-radosgw
#   type: skipped

# Dependent task
- id: hiera-for-standalone-ceph
  type: puppet
  groups: [primary-standalone-ceph-mon,standalone-ceph-mon]
  requires: [deploy_start]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/hiera/hiera.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
  test_pre:
    cmd: python /etc/puppet/modules/osnailyfacter/modular/hiera/hiera_pre.py
  test_post:
    cmd: python /etc/puppet/modules/osnailyfacter/modular/hiera/hiera_post.py


- id: tools-for-standalone-ceph
  type: puppet
  groups: [primary-standalone-ceph-mon, standalone-ceph-mon]
  required_for: [deploy_end]
  requires: [logging-for-standalone-ceph]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/tools/tools.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
  test_post:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/tools/tools_post.rb

- id: netconfig-for-standalone-ceph
  type: puppet
  groups: [primary-standalone-ceph-mon, standalone-ceph-mon]
  required_for: [deploy_end]
  requires: [tools-for-standalone-ceph]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/netconfig/netconfig.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
  test_pre:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/netconfig/netconfig_pre.rb
  test_post:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/netconfig/netconfig_post.rb

- id: connectivity_tests-for-standalone-ceph
  type: puppet
  groups: [primary-standalone-ceph-mon, standalone-ceph-mon]
  required_for: [firewall, hosts-for-standalone-ceph]
  requires: [netconfig-for-standalone-ceph]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/netconfig/connectivity_tests.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
    cwd: /

- id: globals-for-standalone-ceph
  type: puppet
  groups: [primary-standalone-ceph-mon, standalone-ceph-mon]
  required_for: [deploy_end]
  requires: [hiera-for-standalone-ceph]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/globals/globals.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
  test_pre:
    cmd: python /etc/puppet/modules/osnailyfacter/modular/globals/globals_pre.py
  test_post:
    cmd: python /etc/puppet/modules/osnailyfacter/modular/globals/globals_post.py

- id: fuel_pkgs-for-standalone-ceph
  type: puppet
  groups: [primary-standalone-ceph-mon, standalone-ceph-mon]
  requires: [deploy_start]
  required_for: [hiera-for-standalone-ceph]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/fuel_pkgs/fuel_pkgs.pp
    puppet_modules: /etc/puppet/modules
    timeout: 600

- id: logging-for-standalone-ceph
  type: puppet
  groups: [primary-standalone-ceph-mon, standalone-ceph-mon]
  required_for: [deploy_end]
  requires: [globals-for-standalone-ceph]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/logging/logging.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: hosts-for-standalone-ceph
  type: puppet
  groups: [primary-standalone-ceph-mon, standalone-ceph-mon]
  required_for: [deploy_end]
  requires: [netconfig-for-standalone-ceph]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/hosts/hosts.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
  test_pre:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/hosts/hosts_pre.rb
  test_post:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/hosts/hosts_post.rb

# - id: standalone-ceph-radosgw
#   type: puppet
#   groups: [detached-ceph-mon]
#   required_for: [deploy_end, controller_remaining_tasks]
#   requires: [apache, standalone-ceph-mon]
#   parameters:
#     puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/ceph/radosgw.pp
#     puppet_modules: /etc/puppet/modules
#     timeout: 3600
#   test_pre:
#     cmd: ruby /etc/puppet/modules/osnailyfacter/modular/ceph/radosgw_pre.rb
#   test_post:
#     cmd: ruby /etc/puppet/modules/osnailyfacter/modular/ceph/radosgw_post.rb


# - id: standalone-ceph-apache
#   type: puppet
#   groups: [detached-ceph-mon]
#   required_for: [keystone]
#   requires: [openstack-haproxy]
#   parameters:
#     puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/apache/apache.pp
#     puppet_modules: /etc/puppet/modules
#     timeout: 1200
#   test_post:
#     cmd: ruby /etc/puppet/modules/osnailyfacter/modular/apache/apache_post.rb 


#- id: detach-ceph-mon-deployment-puppet
#  type: puppet
#  groups: [detach-ceph-mon]
#  required_for: [deploy_end]
#  requires: [deploy_start]
#  parameters:
#    puppet_manifest: "deploy.pp"
#    puppet_modules: ""
#    timeout: 3600

#- id: detach-ceph-mon-post-deployment-sh
#  type: shell
#  role: [detach-ceph-mon]
#  required_for: [post_deployment_end]
#  requires: [post_deployment_start]
#  parameters:
#    cmd: echo post_deployment_task_executed > /tmp/post_deployment
#    retries: 3
#    interval: 20
#    timeout: 180

#- id: detach-ceph-mon-pre-deployment-sh
#  type: shell
#  role: [detach-ceph-mon]
#  required_for: [pre_deployment_end]
#  requires: [pre_deployment_start]
#  parameters:
#    cmd: echo pre_deployment_task_executed > /tmp/pre_deployment
#    retries: 3
#    interval: 20
#    timeout: 180
